### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [mherbold/starflight#1]
Hi,

Any plans for linux support of this neat remake?

Thanks!

**Comment by mherbold** [comment]
I am not sure what is involved with getting Linux support working.  Unity has support for many platforms, so I guess eventually I'll have to find out what is involved in getting the remake to work on platforms other than Windows.

**Comment by mherbold** [comment]
By the way this is a completely public project - there is no reason why anybody else couldn't make builds for other platforms on their own.  All of the code and art assets are in this GitHub repository.
