### ISSUE TITLE
Add more content to the README file

### ISSUE THREAD

**Issue by aaronfranke** [mherbold/starflight#20]
The README.md file is a bit barebones, it basically says "Contributions welcome, here's website".

It would be nice to have more information in this file, such as:

- [x] Which Starflight games this project is taking inspiration from (just first one? PC version only?)
- [x] Goals & what the finished game would have in it.
- [ ] Possibly screenshots of the current state of the game.
- [x] What Unity version is being used. (I see the project file says 2018.3.0, this should be in README)
- [x] What external libraries does this game use? Instructions for compiling/running the game?
- [ ] Targeting desktops? Mobile? Console? Controllers on PC? (I can help with Linux support)

This doesn't have to be done immediately, but it should be done at some point, especially if you want to be inviting to contributors.

**Comment by mherbold** [comment]
The readme could be your first contribution.  :-)

Answers to your items:

**Which Starflight games this project is taking inspiration from (just first one? PC version only?)**
I am taking inspiration from primarily the CGA and EGA versions of Starflight.

**Goals & what the finished game would have in it.**
All features of the original PC version would be in it, updated to modern graphics.

**Possibly screenshots of the current state of the game.**
All screenshots and videos are on my blog.

**What Unity version is being used. (I see the project file says 2018.3.0, this should be in README)**
The latest version of Unity.

**What external libraries does this game use? Instructions for compiling/running the game?**
No external libraries - this project is completely self-contained.
Build instructions - (1) install unity, (2) open game in unity, (3) hit the play or build button.

**Targeting desktops? Mobile? Console? Controllers on PC? (I can help with Linux support)**
Currently targeting Windows PC, but in theory, it should be buildable for Linux and MacOS out of the box as well, as I believe Unity considers those platforms to be equivalent as far as their build process goes.  I have not tried building for Linux or MacOS yet.  As for mobile support, some work with shaders and scaling the game down (mesh poly/vertex counts) would need to be done, as well as implementing some sort of touch screen input scheme.  I do not plan on doing mobile support myself at this time.  As for controllers on PC - Unity allows you to map controllers to game inputs on the launch screen, so in theory, any PC controller will work.  So far the game only needs input for the 4 directions along with a fire and cancel button.

**Comment by aaronfranke** [comment]
One reason why build instructions and libraries used are important is to clarify if things like this, if they're important or not. Does it matter if the game runs without Unity services?

![1](https://user-images.githubusercontent.com/1646875/52546485-c4636e00-2d8d-11e9-8cfb-54c6dd3cb893.png)

**Comment by mherbold** [comment]
Heya sorry I totally missed your comment here.  The game does not need Unity services at all and will run without it.

**Comment by aaronfranke** [comment]
Because of https://github.com/mherbold/starflight/pull/21 I'll close this issue, screenshots are still missing but we can work on that later perhaps, and the target platforms can of course be up for discussion.
