### ISSUE TITLE
Can't enter hyperspace

### ISSUE THREAD

**Issue by Gamxin** [mherbold/starflight#3]
Ship just flies past map bounds like before instead of loading me into hyperspace.

Also a suggestion I thought would be to increase ship speed, probably twice as fast in system and maybe 1.5x faster in hyperspace?

**Comment by mherbold** [comment]
I incremented the player data version number to force it to start clean.  Try it now.

As for increasing ship speed - that would make the universe feel smaller... I thought you wanted it to feel bigger?  The size of the universe is directly proportional to the speed of the ship.

**Comment by mherbold** [comment]
Poster reported hyperspace works now.
