### ISSUE TITLE
Music Starts Early

### ISSUE THREAD

**Issue by Gamxin** [mherbold/starflight#6]
The system travel music starts a bit early, it starts going once I enter the docking bay, not a big issue but it's worth noting

**Comment by mherbold** [comment]
Are you sure it's the system travel music that is playing?  There is a docking bay music track that should be playing, and it is different than the system travel music.

**Comment by mherbold** [comment]
Gonna close this for now - reopen it if you think it's still an issue.  I think you were just getting confused as to which music track was playing.  :-)
